config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import home,blockedPage

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('hodimlar.urls')),
    path('', home, name='home'),
    path('projects/',include('loyihalar.urls')),
    path('accounts/',blockedPage, name='blocked-page' )
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hodimlar/urls.py
from django.urls import path
from .views import login_view, logoutView, profileView, UserUpdateView, UsersView, create_user,block_user,unblock_user,delete_user,profileView2

app_name = 'hodimlar'

urlpatterns = [
    path('view/', UsersView.as_view(), name='users'),
    path('login/', login_view, name='login'),
    path('logout/', logoutView, name='logout'),
    path('profile/', profileView, name='profile'),
    path('profile/<pk>', profileView2, name='profile2'),
    path('create-user/', create_user, name='create-user'),
    path('update/<pk>', UserUpdateView.as_view(), name='update-user'),
    path('view/block/<pk>', block_user, name='block'),
    path('view/unblock/<pk>', unblock_user, name='unblock'),
    path('view/delete-user/<pk>', delete_user, name='delete-user'),
]

templates/all_projects.html
{% extends 'base.html' %}
{% block content %}
    {% load filters %}
    <section class="bg-light">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Loyihalar</h3>

                <div class="card-tools mb-3">
                    <i style="rotate: 90deg" id="filter-table" class="fa-solid fa-sliders btn btn-outline-dark"></i>

                </div>

                <div class="table-responsive">
                    <div class="card grid-container mt-3" id="filter-container" style="display: none">
                        <label class="grid-item">
                            <input class="cols" name="project_name" type="checkbox"> Loyiha nomi
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_description" type="checkbox"> Loyiha haqida
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_department" type="checkbox"> Tashabbuskor departament
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_blog__blog_name" type="checkbox"> Blok
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_type" type="checkbox"> Loyiha turi
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_size" type="checkbox"> Masshtab
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_level" type="checkbox"> Muhimlilik darajasi
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_speed" type="checkbox"> Muddat darajasi
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_departments" type="checkbox"> Mas'ul departament(lar)
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_team" type="checkbox"> Mas'ul xodim(lar)
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_budget" type="checkbox"> Umumiy loyiha summasi
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_deadline" type="checkbox"> Taxminiy yakunlash sanasi
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_status" type="checkbox"> Loyiha statusi
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_curator" type="checkbox"> Strategiya departamentida
                            biriktirilgan xodim
                        </label>
                        <label class="grid-item">
                            <input class="cols" name="project_spent_money" type="checkbox"> Sarflangan xarajat
                        </label>
                        <button id="apply-changes" class="btn btn-primary">Qo'llash</button>
                    </div>
                    <table class="table table-striped" id="table-projects">
                        <thead>
                        <tr>
                            <th class="text-center">№</th>
                            <th class="text-center">Loyiha nomi</th>
                            <th class="text-center">Loyiha haqida</th>
                            <th class="text-center">Departamenti</th>
                            <th class="text-center">Ma'sul xodim</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for project in projects %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td class="text-center">
                                    <a href="{% url 'get-project' project.pk %}"
                                       style="color: black">{{ project.project_name }}</a>
                                </td>
                                <td>{{ project.project_description }}</td>
                                <td>{{ project.project_department }}</td>
                                <td>{{ project.project_curator.get_full_name }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </section>
    <script type="text/javascript">
        var projects_s = {{ projects_serialized | safe }};
    </script>
    <script>
        console.log(projects_s)
        document.getElementById('filter-table').addEventListener('click', function () {
            var filter = document.getElementById('filter-container');
            if (filter.style.display === 'none') {
                filter.style.display = 'block'
            } else {
                filter.style.display = 'none'
            }
        })
        var cols = []
        var colNames = []
        var thead = ''
        var tbody = ''
        filters = document.querySelectorAll('.cols');
        filters.forEach(value => {
            value.addEventListener('change', function (e) {
                var checked = e.target.checked
                if (checked) {
                    cols.push(value.parentNode.textContent.trim())
                    colNames.push(value.name)
                } else {
                    cols = cols.filter(item => item !== value.parentNode.textContent.trim());
                    colNames = colNames.filter(item => item !== value.name);
                }
            })
        })

        document.getElementById('apply-changes').addEventListener('click', function () {
            document.getElementById('filter-container').style.display = 'none'
            cols.forEach(col => {
                thead += `<th>${col}</th>`
            })
            for (i = 0; i < projects_s.length; i++) {
                var tds = ''
                colNames.forEach(value => {
                    tds += `<td><a href=${window.location.pathname.replace('all',projects_s[i].pk)} style="color:#000;">${projects_s[i].fields[value]}</a></td>`
                })
                tbody += `<tr>${tds}</tr>`
            }


            document.getElementById('table-projects').innerHTML = `<thead><tr>${thead}</tr></thead><tbody>${tbody}</tbody>`
        })

    </script>

{% endblock content %}

templates/base.html
{% load static %}
{% load filters %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>PMO system</title>
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Roboto:300,400&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500&display=swap" rel="stylesheet">

    <link href="https://fonts.googleapis.com/css?family=Source+Serif+Pro:400,600&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'extra/fonts/icomoon/style.css' %}">

    <link rel="stylesheet" href="{% static 'extra/css/select2.min.css' %}">
        <link rel="stylesheet" href="{% static 'extra/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'static/css/style.css' %}">
      <link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
  <link rel="stylesheet" href="{% static  'plugins/datatables-responsive/css/responsive.bootstrap4.min.css'%}">
  <link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <script>
            var lists = JSON.parse('{{ labels | escapejs }}')
            var token = '{{ csrf_token | escapejs }}';
        </script>
        <ul class="navbar-nav">
            <li class="nav-item d-none d-sm-inline-block">
                <a href="{% url 'home' %}" class="nav-link">Home</a>
            </li>
        </ul>
    </nav>

    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <a href="{% url 'home' %}" class="brand-link">
            <img src="{% static 'dist/img/AdminLTELogo.png' %}" alt="Logo"
                 class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">PMO system</span>
        </a>
        <div class="sidebar">
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    {% if user.avatar.url %}
                    <img src="{{ user.avatar.url }}" class="img-circle elevation-2"
                         alt="User Image">
                    {% else %}
                                            <img src="https://static.vecteezy.com/system/resources/previews/023/089/807/non_2x/simple-user-icon-the-icon-can-be-used-for-websites-print-templates-presentation-templates-illustrations-etc-free-vector.jpg" class="img-circle elevation-2"
                         alt="User Image">
                    {% endif %}
                </div>
                <div class="info">
                    <a href="{% url 'hodimlar:profile' %}" class="d-block">{{ user.get_full_name }}</a>
                </div>
            </div>

            <div class="form-inline">
                <div class="input-group" data-widget="sidebar-search">
                    <input class="form-control form-control-sidebar" type="search" placeholder="Search"
                             aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-sidebar">
                            <i class="fas fa-search fa-fw"></i>
                        </button>
                    </div>
                </div>
            </div>
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <li class="nav-item">
                        <a href="{% url 'hodimlar:profile' %}" class="nav-link">
                            <i class="fa-solid fa-user" style="color: #fafafa;margin-right: 2%"></i>
                            <p>
                                Profil
                            </p>
                        </a>
                    </li>
                    {% if user.role == 'Admin' %}
                                        <li class="nav-item">
                        <a href="{% url 'hodimlar:users' %}" class="nav-link">
                            <i class="fa-solid fa-users" style="color: #fafafa;margin-right: 2%"></i>
                            <p>
                                Foydalanuvchilar
                            </p>
                        </a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'all-projects' %}" class="nav-link">
                            <i class="fa-solid fa-file-invoice" style="color: #fafafa;margin-right: 2%"></i>
                            <p>
                                Barcha loyihalar
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'my-projects' %}" class="nav-link">
                            <i class="fa-solid fa-file-contract" style="color: #fafafa;margin-right: 2%"></i>
                            <p>
                                Mening loyihalarim
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'owned-projects' %}" class="nav-link">
                            <i class="fa-solid fa-briefcase" style="color: #fafafa;margin-right: 2%"></i>
                            <p>
                                Loyiha egasi
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'qualification' %}" class="nav-link">
                            <i class="fa-solid fa-square-poll-vertical" style="color: #fafafa;margin-right: 2%"></i>
                            <p>
                                Kvalifikatsiya
                            </p>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'spending' %}" class="nav-link">
                            <i class="fa-solid fa-building-columns" style="color: #fafafa;margin-right: 2%"></i>
                            <p>
                                Xarajatlar
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </aside>
    <div class="content-wrapper">
        {% block content %}
        {% endblock content %}
    </div>
</div>
    <script src="https://telegram.org/js/telegram-web-app.js?56"></script>

<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<script src="{% static 'plugins/chart.js/Chart.min.j' %}s"></script>
<script src="{% static 'dist/js/demo.js' %}"></script>
<script src="{% static 'dist/js/pages/dashboard3.js' %}"></script>
<script src="{% static 'static/js/script.js' %}">
</script>
    <script src="{% static 'extra/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'extra/js/popper.min.js' %}"></script>
    <script src="{% static 'extra/js/select2.min.js' %}"></script>
    <script src="{% static 'extra/js/main.js' %}"></script>
    <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>

</body>
</html>

templates/blocked_page.html
{% extends 'base.html' %}

{% block content %}

         <div class="container py-5">
          <div class="row">
               <div class="col-md-2 text-center">
                    <p><i class="fa fa-exclamation-triangle fa-5x"></i><br/>Status Code: 403</p>
               </div>
               <div class="col-md-10">
                    <h3>OPPSSS!!!! Kechirasiz...</h3>
                    <p>Siz sayt qoidalarini buzganingiz uchun sayt administratorlari tomonidan bloklangansiz </p>
                    <a class="btn btn-danger" href="javascript:history.back()">Ortga qaytish</a>
               </div>
          </div>
     </div>

{% endblock content %}

templates/create_project.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
    <div class="container">
    <div class="card">
        <div class="card-header">
            <h1>Loyiha yaratish</h1>
        </div>
    <div class="card-body">
        <form method="post">
                                                {% csrf_token %}
                        {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary d-block">Yaratish</button>
        </form>
    </div>
    </div>
    </div>
    
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

{% if user.is_authenticated %}
<div class="content" style="width: 100%; height: 100%;">
    <script>
        // Telegram WebApp API integration
        const tg = window.Telegram.WebApp;

        // Initialize Telegram WebApp
        tg.ready();

        // Customize header color
        tg.setHeaderColor("bg_color", "#0088cc");

        // Set background color
        tg.setBackgroundColor("#f3f3f3");

        // Show MainButton
        tg.MainButton.setText("Click Me!");
        tg.MainButton.show();

        // Handle MainButton click
        tg.MainButton.onClick(() => {
            // Example: Send data to the bot
            tg.sendData(JSON.stringify({ action: "clicked_main_button" }));

            // Optional: Close the WebApp
            tg.close();
        });

        // Clean up when the page unloads
        window.addEventListener("beforeunload", () => {
            tg.MainButton.offClick();
        });
    </script>

    <div class="container-fluid" style="height: 100%; width: 100%;">
        <div class="row mb-4">
            <!-- Example Chart Section -->
            <div class="col-lg-6 mt-3">
                <div class="card">
                    <div class="card-header border-0">
                        <div class="d-flex justify-content-between">
                            <h3 class="card-title">Bloklardagi departamentlar soni: {{ departments }} ta</h3>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="position-relative mb-4">
                            <canvas id="visitors-chart" height="200"></canvas>
                        </div>
                    </div>
                </div>
            </div>
            
            <!-- Add Additional Sections Here -->
        </div>

        <!-- Example Table Section -->
        <div class="card">
            <div class="card-header border-0">
                <div class="d-flex justify-content-between">
                    <h3 class="card-title">Atamalar to'liq nomi</h3>
                </div>
            </div>
            <div class="card-body">
                <table class="table">
                    <tr>
                        <th>BB</th>
                        <td>Biznes bloki</td>
                    </tr>
                    <tr>
                        <th>BR</th>
                        <td>Boshqaruv Raisi</td>
                    </tr>
                    <!-- Add More Rows as Needed -->
                </table>
            </div>
        </div>
    </div>
</div>
{% else %}
<div class="alert alert-danger">
    Siz tizimga kirmagansiz. Iltimos, kirish uchun ro'yxatdan o'ting.
</div>
{% endif %}

{% endblock content %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <div class="row">
 <div class="col-3">

 </div>
     <div class="col-5" style="margin-top: 7%" >
  <div class="card mt-4" style="width: 500px;height: 400px">
    <div class="card-body login-card-body">
      <p class="login-box-msg">Shaxsiy kabinetga kirish</p>

      <form action="" method="post">
          {% csrf_token %}
        <div class="input-group mb-3" style="margin-top: 10%">
            {{ form.username }}
            <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-envelope"></span>
            </div>
          </div>
        </div>
        <div class="input-group mb-3">
            {{ form.password }}
          <div class="input-group-append">
            <div class="input-group-text">
              <span class="fas fa-lock"></span>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-12">
            <button type="submit" class="btn btn-primary btn-block">Kirish</button>
          </div>
        </div>
      </form>
    </div>
  </div>
     </div>
 <div class="col-3">

 </div>
 </div>
{% endblock content %}

templates/my-projects.html
{% extends 'base.html' %}
{% block content %}
    {% load filters %}
    <section class="content bg-light">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Loyihalar</h3>

                <div class="card-tools">
                    <a href="{% url 'create-project' %}"> <i
                            class="fa-solid fa-circle-plus btn btn-outline-dark"></i></a>
                </div>
            </div>
            <div class="card-body p-0" style="overflow-x: auto">
                <table class="table table-striped projects">
                    <thead>
                    <tr>
                        <th scope="col">
                            No
                        </th>
                        <th scope="col">
                            Loyiha nomi
                        </th>
                        <th scope="col">
                            Loyiha haqida
                        </th>
                        <th scope="col">
                            Tashabbuskor departament
                        </th>

                                          <th scope="col" class="text-center" style="width: 10%">
                            Muddati

                        </th>
                                                                  <th scope="col">
                            Summasi

                        </th>
                                                                                          <th scope="col" class="text-center">
                            Biriktirilgan xodim

                        </th>

                    </tr>
                    </thead>
                    <tbody>
                    {% for project in projects %}
                        <tr>
                            <td>
                                {{ forloop.counter }}
                            </td>
                            <td>
                                <a href="{% url 'get-project' project.pk %}" style="color: black">
                                    {{ project.project_name }}
                                </a>
                            </td>
                            <td>
                                {{ project.project_description }}
                            </td>
                            <td >
                                {{ project.project_department }}
                            </td>
                                                                                    <td class="project-state">
                                <p>{{ project.project_deadline | date:"m, d, Y" }}</p>
                            </td>

                                                                                                         <td class="project-state">
                                <p>{{ project.project_budget}}</p>
                            </td>

                                                                                                                            <td class="project-state">
                                <p>{{ project.project_curator.get_full_name}}</p>
                            </td>

                            <td class="project-actions text-right">
<ul style="list-style: none">
    <li>
        <a class="btn btn-primary btn-sm" href="{% url 'my-projects-detail' project.pk %}">
            <i class="fas fa-folder"></i>
        </a>
    </li>
    <li>
        <a class="btn btn-info btn-sm" href="{% url 'update-project' project.pk %}">
            <i class="fas fa-pencil-alt"></i>
        </a>
    </li>
    <li>
        <button id="{{ project.pk }}" type="button" class="btn btn-danger btn-sm delete-button" data-toggle="modal" data-target="#myModal">
            <i class="fas fa-trash"></i>
        </button>
    </li>
</ul>

                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title">Chindan ham loyihani o'chirasizmi ?</h4>
                    </div>
                    <div class="modal-footer">
                        <button id="confirm" type="button" class="btn btn-primary" data-dismiss="modal">Ha</button>
                        <button id="cancel" type="button" class="btn btn-danger" data-dismiss="modal">Bekor qilish
                        </button>
                    </div>
                </div>

            </div>
        </div>

    </section>


{% endblock content %}

templates/qualification.html
{% extends 'base.html' %}

{% block content %}
<h1>Kvalifikatsiya</h1>
{% endblock content %}

templates/spendings.html
{% extends 'base.html' %}

{% block content %}

    <h1>Xarajatlar</h1>
    
{% endblock content %}

templates/users.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-12">
        <div class="card shadow-2-strong"
             style="background-color: #ffffff; height: 100dvh">
            <div class="card-header">
                <div class="row mt-3">
                    <label for="inputEmail3" class="col-1 col-form-label">Tanlang</label>
                    <div class="col-6">
                        <select type="text" class="form-control" id="input-select">
                            <option>Hech nima tanlanmagan</option>
                            <option id="detailed" name="batafsil">Batafsil</option>
                            <option id="block" name="block">Bloklash</option>
                            <option id="unblock" name="unblock">Blokdan ochish</option>
                        </select>
                    </div>
                    <div class="col-2">
                        <button id="do-button" class="btn btn-danger" style="display: inline">Go</button>
                        <i onclick="location.href = '{% url 'hodimlar:create-user' %}'" id="add-user" class="fa-solid fa-circle-plus btn btn-outline-dark" ></i>
                        <i id="delete-button" class="fa-solid fa-trash-can btn btn-outline-dark"></i>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <div class="table-responsive" style="overflow-x: auto">
                    <table class="table table-borderless mb-0">
                        <thead>
                        <tr>
                            <th scope="col"></th>
                            <th scope="col">№</th>
                            <th scope="col">FIO</th>
                            <th scope="col">STATUS</th>
                            <th scope="col">ROLI</th>
                            <th scope="col">RAQAMI</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% with num=0 %}
                            {% for user in object_list %}
                                <tr>
                                    <th scope="row">
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value=""
                                                   id="{{ user.id }}"/>
                                        </div>
                                    </th>
                                    <td>{{ forloop.counter }}</td>
                                    <td><a href="{% url 'hodimlar:profile2' user.id %}" style="color:#000;">{{ user.get_full_name }}</a></td>
                                    {% if user.status == 'Active' %}
                                        <td><i class="fa-solid fa-circle"
                                               style="color: green;margin-left: 10%"></i></td>
                                    {% else %}
                                        <td><i class="fa-solid fa-circle"
                                               style="color: red;margin-left: 10%"></i></td>
                                    {% endif %}
                                    <td>{{ user.role }}</td>
                                    <td>{{ user.phone }}</td>
                                </tr>
                            {% endfor %}
                        {% endwith %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}